#!/bin/sh
set -e

if [ "$1" = purge ] || [ "$1" = remove ]; then
  rm -rf /var/run/screen
fi

if [ "$1" = purge ]; then
  rm -vf /etc/tmpfiles.d/screen-cleanup.conf

  # LP #1462692
  rm -f /lib/systemd/system/screen-cleanup.service
  rmdir -p --ignore-fail-on-non-empty /lib/systemd/system
fi

if [ "$1" = disappear ]; then
  remove-shell /usr/bin/screen || true
fi

#DEBHELPER#
